title: My Awesome Site
email: evitasimaresi@gmail.com
description: Architect and developer and engineer based in southern europe. Creative mind on developing, architecture, product design, graphic design and whatever has to be engineered...
baseurl: ""
url: ""
github_username: evitasimaresi

exclude: [README.md, fields.html, projects.html, _fields/]

collections:
  #This is the categories of each group set, like architecture, web, product design etc....
  fields:
    output: true

defaults:
  -scope:
    path: ""
    type: "projects"
  values:
    layout: "projects"
  -scope:
    path: ""
    type: "post"
  values:
    layout: "post"
  -scope:
    path: ""
  values:
    layout: "default"
    -scope:
    path: ""
    type: "field"
  values:
    layout: "field"
    -scope:
    path: ""
    type: "grid"
  values:
    layout: "grid"